# Generated by Django 4.1.7 on 2023-04-07 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToCreateImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('gender', models.TextField(max_length=50)),
                ('skin_color', models.TextField(max_length=50)),
                ('age', models.TextField(max_length=50)),
                ('hair', models.TextField(max_length=50)),
                ('eyes', models.TextField(max_length=50)),
                ('eyebrows', models.TextField(max_length=50)),
                ('jaw', models.TextField(max_length=50)),
                ('nose', models.TextField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'keywords',
                'verbose_name_plural': 'keywords',
                'ordering': ['-created_date'],
            },
        ),
    ]
